version: '3.1'
services:
    jenkins:
        container_name: jenkins-master
        ports:
            - '8080:8080'
            - '50000:50000'
        build: master/
        volumes:
            - ./jenkins_home:/var/jenkins_home
