pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                build()
            }
        }

        stage('Test') {
            steps {
                unit_test()
            }
        }

        stage('SCA') {
            steps {
                static_code_analysis()
            }
        }                
    }
}